# Generated by Django 2.2.14 on 2020-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_aabc"),
    ]

    operations = [
        migrations.AddField(
            model_name="aabc",
            name="jutygjhgjhgfhjgj",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
