# Generated by Django 2.2.14 on 2020-07-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aabc_jutygjhgjhgfhjgj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aabc',
            old_name='jutygjhgjhgfhjgj',
            new_name='gfhfhgfhg',
        ),
    ]
